import io
import time
from html import escape

import streamlit as st
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor
from dotenv import load_dotenv

load_dotenv()

st.set_page_config(
    page_title="ResearchMind · AI Research Agent",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="collapsed",
)

CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Mono:wght@300;400;500&family=DM+Sans:wght@300;400;500&display=swap');
:root { color-scheme: dark; }
html, body, [class*="css"] { font-family:'DM Sans',sans-serif; }
.stApp, [data-testid="stAppViewContainer"], [data-testid="stMain"] {
  background:#0a0a0f !important; color:#e8e4dc !important;
}
.block-container { max-width:1200px; padding:1.5rem 2rem 3rem; }
.stMarkdown, .stMarkdown p, .stMarkdown li, .stMarkdown h1, .stMarkdown h2,
.stMarkdown h3, [data-testid="stMarkdownContainer"] { color:#e8e4dc; }
.hero { text-align:center; padding:2.5rem 0 1.6rem; }
.eyebrow { font-family:'DM Mono',monospace; font-size:.72rem; letter-spacing:.22em;
  color:#ff8c32; text-transform:uppercase; margin-bottom:.7rem; }
.hero h1 { font-family:'Syne',sans-serif; font-size:clamp(2.5rem,6vw,4.5rem);
  font-weight:800; line-height:1.05; color:#f0ebe0; margin:0; }
.hero h1 span { color:#ff8c32; }
.hero p { color:#b6afa5; max-width:620px; margin:1rem auto 0; line-height:1.7; }
.rule { height:1px; margin:1.3rem 0 2rem; background:linear-gradient(90deg,transparent,rgba(255,140,50,.4),transparent); }
.panel { background:#12121a; border:1px solid rgba(255,140,50,.2); border-radius:14px; padding:1rem 1.2rem; }
.panel-title { color:#ff8c32; font-family:'DM Mono',monospace; font-size:.76rem;
  letter-spacing:.12em; text-transform:uppercase; margin-bottom:.7rem; }
.stTextInput input, .stChatInput textarea { background:#17171f !important; color:#f0ebe0 !important;
  -webkit-text-fill-color:#f0ebe0 !important; border-color:rgba(255,140,50,.35) !important; }
.stTextInput label { color:#ffb16f !important; }
.stButton > button, .stDownloadButton > button { border:0; border-radius:9px;
  background:linear-gradient(135deg,#ff8c32,#ff5a1a); color:#0a0a0f;
  font-weight:700; }
.stButton > button:hover, .stDownloadButton > button:hover { border:0; color:#0a0a0f; }
[data-testid="stExpander"], [data-testid="stExpander"] details { background:#12121a; color:#e8e4dc; }
.stChatMessage { background:#15151e; }
small, .stCaption { color:#b6afa5 !important; }
@media(max-width:768px) { .block-container {padding:.8rem .8rem 2rem;} .hero {padding:1.5rem 0 1rem;} }
</style>
"""
st.markdown(CSS, unsafe_allow_html=True)

st.markdown(
    """
    <div class="hero">
      <div class="eyebrow">Multi-Agent AI System</div>
      <h1>Research<span>Mind</span></h1>
      <p>Four specialized AI stages search, read, write, and critique to produce a clear research report.</p>
    </div>
    <div class="rule"></div>
    """,
    unsafe_allow_html=True,
)

def build_docx(topic: str, report: str, feedback: str) -> bytes:
    doc = Document()
    for section in doc.sections:
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin = Inches(0.9)
        section.right_margin = Inches(0.9)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("ResearchMind Report")
    run.bold = True
    run.font.size = Pt(23)
    run.font.color.rgb = RGBColor(255, 140, 50)

    sub = doc.add_paragraph(f"Topic: {topic}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date = doc.add_paragraph(f"Generated: {time.strftime('%B %d, %Y')}")
    date.alignment = WD_ALIGN_PARAGRAPH.CENTER

    for line in report.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith(("- ", "* ")):
            doc.add_paragraph(line[2:], style="List Bullet")
        else:
            doc.add_paragraph(line)

    if feedback.strip():
        doc.add_page_break()
        doc.add_heading("Critic Feedback", level=1)
        for line in feedback.splitlines():
            line = line.strip()
            if line.startswith(("- ", "* ")):
                doc.add_paragraph(line[2:], style="List Bullet")
            elif line:
                doc.add_paragraph(line)

    doc.add_paragraph("Generated by ResearchMind · Multi-Agent AI System")
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def content_text(message) -> str:
    content = getattr(message, "content", "")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        pieces = []
        for part in content:
            if isinstance(part, dict) and part.get("text"):
                pieces.append(str(part["text"]))
            elif isinstance(part, str):
                pieces.append(part)
        return "\n".join(pieces) or str(content)
    return str(content)


def run_pipeline(topic: str) -> dict:
    # Import lazily so a missing key is shown as an in-app error, not a blank crash.
    from agents import build_reader_agent, build_search_agent, writer_chain, critic_chain, safe_invoke

    results = {}
    with st.spinner("🔍 Search Agent is finding relevant sources…"):
        search_agent = build_search_agent()
        search_result = safe_invoke(
            search_agent,
            {"messages": [("user", f"Find recent, reliable information about: {topic}")]},
            delay=0.2,
        )
        results["search"] = content_text(search_result["messages"][-1])

    with st.spinner("📄 Reader Agent is extracting a relevant source…"):
        reader_agent = build_reader_agent()
        reader_result = safe_invoke(
            reader_agent,
            {
                "messages": [
                    (
                        "user",
                        f"Choose the single most relevant URL and scrape it once for this topic: {topic}\n\n"
                        f"Search results:\n{results['search'][:5000]}",
                    )
                ]
            },
            delay=0.2,
        )
        results["reader"] = content_text(reader_result["messages"][-1])

    research = (
        f"SEARCH RESULTS:\n{results['search']}\n\n"
        f"SCRAPED CONTENT:\n{results['reader']}"
    )
    with st.spinner("✍️ Writer is drafting the report…"):
        results["writer"] = safe_invoke(
            writer_chain, {"topic": topic, "research": research}, delay=0.2
        )

    with st.spinner("🧐 Critic is reviewing the report…"):
        results["critic"] = safe_invoke(
            critic_chain, {"report": results["writer"]}, delay=0.2
        )
    results["research"] = research
    return results


if "results" not in st.session_state:
    st.session_state.results = {}
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

col_input, col_pipeline = st.columns([1.15, 0.85], gap="large")
with col_input:
    st.markdown('<div class="panel-title">Start a new research task</div>', unsafe_allow_html=True)
    topic = st.text_input(
        "Research topic",
        placeholder="e.g. Quantum computing breakthroughs in 2026",
        key="topic_input",
    )
    run_button = st.button("⚡ Run Research Pipeline", use_container_width=True)
    st.caption("Examples: LLM agents · CRISPR gene editing · Fusion energy progress")

with col_pipeline:
    st.markdown('<div class="panel-title">Pipeline</div>', unsafe_allow_html=True)
    for number, title, description in [
        ("01", "Search Agent", "Finds relevant web sources"),
        ("02", "Reader Agent", "Extracts useful page content"),
        ("03", "Writer Chain", "Creates the research report"),
        ("04", "Critic Chain", "Reviews the report"),
    ]:
        st.markdown(
            f'<div class="panel" style="margin-bottom:.6rem"><b style="color:#ff8c32">{number}</b> '
            f'<b>{escape(title)}</b><br><span style="color:#b6afa5">{escape(description)}</span></div>',
            unsafe_allow_html=True,
        )

if run_button:
    if not topic.strip():
        st.warning("Please enter a research topic first.")
    else:
        st.session_state.results = {}
        st.session_state.chat_history = []
        try:
            st.session_state.results = run_pipeline(topic.strip())
            st.success("Research pipeline completed.")
        except Exception as exc:
            st.error(
                f"Research pipeline failed: {type(exc).__name__}: {exc}\n\n"
                "Check that GROQ_API_KEY and TAVILY_API_KEY are set in .env, "
                "then restart Streamlit."
            )

results = st.session_state.results
if results:
    st.markdown('<div class="rule"></div><h2>Results</h2>', unsafe_allow_html=True)

    with st.expander("🔍 Search Results", expanded=False):
        st.markdown(results.get("search", "No search output available."))
    with st.expander("📄 Scraped Content", expanded=False):
        st.markdown(results.get("reader", "No scraped content available."))

    st.markdown('<div class="panel-title">Final Research Report</div>', unsafe_allow_html=True)
    st.markdown(results.get("writer", "No report was generated."))
    md_col, doc_col = st.columns(2)
    with md_col:
        st.download_button(
            "⬇ Download Report (.md)",
            data=results.get("writer", ""),
            file_name=f"research_report_{int(time.time())}.md",
            mime="text/markdown",
            use_container_width=True,
        )
    with doc_col:
        st.download_button(
            "⬇ Download Report (.docx)",
            data=build_docx(
                st.session_state.get("topic_input", "Research"),
                results.get("writer", ""),
                results.get("critic", ""),
            ),
            file_name=f"research_report_{int(time.time())}.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            use_container_width=True,
        )

    st.markdown('<div class="rule"></div><div class="panel-title">Critic Feedback</div>', unsafe_allow_html=True)
    st.markdown(results.get("critic", "No critic feedback available."))

    st.markdown('<div class="rule"></div><h2>💬 Ask About This Research</h2>', unsafe_allow_html=True)
    for message in st.session_state.chat_history:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    question = st.chat_input("Ask a follow-up question about the report…")
    if question:
        st.session_state.chat_history.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)
        try:
            from agents import qa_chain, safe_invoke
            with st.chat_message("assistant"):
                with st.spinner("Thinking…"):
                    answer = safe_invoke(
                        qa_chain,
                        {
                            "report": results.get("writer", ""),
                            "research": results.get("research", ""),
                            "question": question,
                        },
                        delay=0.2,
                    )
                st.markdown(answer)
            st.session_state.chat_history.append({"role": "assistant", "content": answer})
        except Exception as exc:
            st.error(f"Could not answer this question: {type(exc).__name__}: {exc}")

st.markdown(
    '<div style="text-align:center;color:#81796f;font-size:.75rem;margin-top:3rem">'
    'ResearchMind · LangChain multi-agent research system</div>',
    unsafe_allow_html=True,
)
